### ISSUE TITLE
[Bug] FasterGameLoading conflicts with Music Expanded Framework

### ISSUE THREAD

**Issue by Ankaleri** [Taranchuk/FasterGameLoading#1]
Whenever I load a map, Music Expanded Framework tries to play background music, fails to do so, and throws a bunch of errors. 

What fixes the problem: 
- removing MEF; 
- disabling "Prevent long event loading during startup" in FGL settings.

Logs:
MEF throws different types of error depending of whether its "Vanilla Music Update" setting is enabled (music plays periodically) or disabled (music plays constantly).
If enabled:
https://gist.github.com/HugsLibRecordKeeper/5a2d38fcb62a2f520e00027e5521054c
If disabled:
https://gist.github.com/HugsLibRecordKeeper/539fea126acf17abaaa4dd497c22e24b

**Comment by Slemaire-PNI** [comment]
Just throwing it out there that I use both currently and don't have that problem.

**Comment by Taranchuk** [comment]
Yeah, I removed the long event actions patches which solves this issue
