### ISSUE TITLE
Random Furniture Items are White (Missing Material Color)

### ISSUE THREAD

**Issue by Slemaire-PNI** [Taranchuk/FasterGameLoading#3]
Sorry for the lack of error message but I couldn't find anything in the log about why this might be happening.  It happens with no other mods installed except prepatcher.

If it helps, here's the furniture items I've noticed.  Most of everything else is fine.
- Slab Beds
- Small Research Bench
- Stonecutter Bench
- Artist Bench

**Comment by Taranchuk** [comment]
Can you post a hugslib log?

**Comment by Slemaire-PNI** [comment]
Sure what is the log location?

**Comment by Taranchuk** [comment]
No log location, it just lets you generate one. Install Hugslib mod, enable
dev mode, press ctrl-f12 or ctrl-shift-f12

вт, 6 февр. 2024 г., 00:06 Slemaire-PNI ***@***.***>:

**Comment by Slemaire-PNI** [comment]
Hugslib says unable to establish connection, probably regional or a firewall somewhere.  Is it just the player.log file it uploads?  Here it is if it's helpful. 
[Player.log](https://github.com/Taranchuk/FasterGameLoading/files/14173399/Player.log)

Pic
[
![Untitled](https://github.com/Taranchuk/FasterGameLoading/assets/60244073/846a63f9-f3bd-4473-882b-55bff069b94b)
](url)

I misspoke earlier, the one mod enabled was Harmony.  And the problem is with harmony - when harmony isn't in the modlist everything works fine.  This only happens with Harmony and only when the second option is enabled.

**Comment by Taranchuk** [comment]
What second option?

вт, 6 февр. 2024 г., 02:55 Slemaire-PNI ***@***.***>:

**Comment by Slemaire-PNI** [comment]
The second feature of faster game loading, in it's options.

**Comment by Taranchuk** [comment]
Okay, what's the name of the option? It's been a while really since I worked on the mod

**Comment by Taranchuk** [comment]
Okay, the log looks weird, I suppose it's not a steam RW version? Is it a pirate version? Could you try to make sure you are on the latest game version and that the game is installed correctly?

**Comment by Slemaire-PNI** [comment]
It's the latest version.  I got this from a key site that's why it's not in
the steam path.  I haven't seen any updates yet, this is the latest
download.

**Comment by Taranchuk** [comment]
So I can't reproduce this issue on my end. With a minimal mod order and with all the mod options enabled.
![image](https://github.com/Taranchuk/FasterGameLoading/assets/24846741/db3d46b2-00c8-4416-aa9d-53e25913ba23)

**Comment by Taranchuk** [comment]
I would say, issue lies in your game version/install.
