### ISSUE TITLE
Furnitures like beds are white

### ISSUE THREAD

**Issue by Tallyhallfan2** [Taranchuk/FasterGameLoading#4]
Hello, I made an account to tell you that the furniture in-game is colored white.

**Comment by Taranchuk** [comment]
Can you post a hugslib log? And do you have a Steam game version?

**Comment by Tallyhallfan2** [comment]
Well I don't have the steam version. Mine is a pirated version and I'm not
an expert of this modding thing but here's the log: (I know pirating is bad
but please bare with me I dont want any insults towards me anymore for
pirating)

RimWorld 1.4.3901 rev238
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
RimWorld.VersionControl:LogVersionNumber ()
Verse.Root:CheckGlobalInit ()
Verse.Root:Start ()
Verse.Root_Entry:Start ()

[HugsLib] version 10.0.1
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
HugsLib.Utils.ModLogger:Message (string,object[])
HugsLib.HugsLibController:InitializeController ()
HugsLib.HugsLibController:EarlyInitialize ()
HugsLib.Core.HugsLibMod:.ctor (Verse.ModContentPack)
System.Reflection.MonoCMethod:InternalInvoke (object,object[])
System.Reflection.MonoCMethod:DoInvoke
(object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MonoCMethod:Invoke
(System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.RuntimeType:CreateInstanceImpl
(System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Threading.StackCrawlMark&)
System.Activator:CreateInstance
(System.Type,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[])
System.Activator:CreateInstance (System.Type,object[])
Verse.LoadedModManager:CreateModClasses ()
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal
(System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run
(System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run
(System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

Starting loading graphics: 1189 - 3/16/2024 6:55:43 PM
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
FasterGameLoading.DelayedActions/<PerformActions>d__6:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext
(System.Collections.IEnumerator,intptr)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
FasterGameLoading.Startup/<>c:<Postfix>b__1_1 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

Finished loading graphics - 3/16/2024 6:55:43 PM
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
FasterGameLoading.DelayedActions/<PerformActions>d__6:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext
(System.Collections.IEnumerator,intptr)

Starting loading icons: 1951 - 3/16/2024 6:55:43 PM
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
FasterGameLoading.DelayedActions/<PerformActions>d__6:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext
(System.Collections.IEnumerator,intptr)

Finished loading icons - 3/16/2024 6:55:43 PM
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
FasterGameLoading.DelayedActions/<PerformActions>d__6:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext
(System.Collections.IEnumerator,intptr)

Loading game from file New Arrivals1 with mods:
  - brrainz.harmony
  - Taranchuk.FasterGameLoading
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - Ludeon.RimWorld.Biotech
  - UnlimitedHugs.HugsLib
  - m00nl1ght.UnofficialUpdates.HugsLogPublisher
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow (string)
Verse.Root_Play/<>c:<Start>b__1_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal
(System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run
(System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run
(System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

Found texture Table1x2_north in another atlas group than requested (found
in Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture TreeDragoA in another atlas group than requested (found in
Misc_False, requested in Plant)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
RimWorld.Plant:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Column in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Urn in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture HospitalBed_south in another atlas group than requested
(found in Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Bedroll_south in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Bed_south in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture LargeSteleF in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Graphic_Random:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Urn in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Column in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Sarcophagus_north in another atlas group than requested
(found in Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Urn in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture LargeSteleD in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Graphic_Random:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

Found texture Urn in another atlas group than requested (found in
Misc_False, requested in Building)!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Verse.GlobalTextureAtlasManager:TryGetStaticTile
(Verse.TextureAtlasGroup,UnityEngine.Texture2D,Verse.StaticTextureAtlasTile&,bool)
Verse.Graphic:TryGetTextureAtlasReplacementInfo
(UnityEngine.Material,Verse.TextureAtlasGroup,bool,bool,UnityEngine.Material&,UnityEngine.Vector2[]&,UnityEngine.Color32&)
Verse.Graphic:Print (Verse.SectionLayer,Verse.Thing,single)
Verse.Thing:Print (Verse.SectionLayer)
Verse.ThingWithComps:Print (Verse.SectionLayer)
Verse.SectionLayer_ThingsGeneral:TakePrintFrom (Verse.Thing)
Verse.SectionLayer_Things:Regenerate ()
Verse.Section:RegenerateAllLayers ()
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__148_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()

[HugsLib][ERR] Exception during PrepareLogData:
System.UnauthorizedAccessException: Access to the path "D:\Programs
stupid\DONT TOUCH\tmp66e2f5ec.tmp" is denied.
  at System.IO.File.Delete (System.String path) [0x00073] in
<eae584ce26bc40229c1b1aa476bfa589>:0
  at HugsLib.Logs.LogPublisher.GetLogFileContents () [0x0004d] in
<4a46802aeab646ab99159f7eecb6b57e>:0
  at HugsLib.Logs.LogPublisher.PrepareLogData () [0x00002] in
<4a46802aeab646ab99159f7eecb6b57e>:0
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
HugsLib.Utils.ModLogger:ReportException
(System.Exception,string,bool,string)
HugsLib.Logs.LogPublisher:PrepareLogData ()
HugsLib.Logs.LogPublisher:BeginUpload ()
HugsLib.Logs.LogPublisher:OnPublishConfirmed ()
HugsLib.Logs.Dialog_PublishLogsOptions:OnAcceptKeyPressed ()
HugsLib.Logs.Dialog_PublishLogsOptions:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate
(UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

[image: srry im on pc.PNG]

**Comment by Tallyhallfan2** [comment]
also I reinstalled the game again so this is a fresh start.... sorry
english isnt my first language

**Comment by Tallyhallfan2** [comment]
version number is: v1.4.3901

**Comment by Tallyhallfan2** [comment]
also sorry for late reply I was busy with my homework

**Comment by Tallyhallfan2** [comment]
another thing is the furniture were rendered properly like its no color
white without harmony

**Comment by Tallyhallfan2** [comment]
also I reinstalled the game again so this is a fresh start.... sorry
> english isnt my first language

**Comment by Tallyhallfan2** [comment]
sorry english isnt my first language

**Comment by Taranchuk** [comment]
Okay, it's the same issue as it was there
https://github.com/Taranchuk/FasterGameLoading/issues/3
Issue with your pirated game

**Comment by Tallyhallfan2** [comment]
Do you perhaps have an early version of the mod?

**Comment by Taranchuk** [comment]
Yeah, this repo. Try looking in commits, you can browse and download versions

**Comment by Tallyhallfan2** [comment]
Thank you!
